In [2]:
# TODO 1: import yfinance, numpy, matplotlib
# TODO 2: download SPY from 2020-01-01, auto_adjust=True, store in df
# TODO 3: print the first 5 rows and the shape
# TODO 4: make a column "ret" = daily % change of Close
# TODO 5: make a column "vol20" = 20-day rolling std of ret, annualized
# TODO 6: plot Close and vol20 as two stacked charts
# TODO 7: histogram of ret with 50 bins
# TODO 8: print the date with the highest vol20
# TODO 9: print the worst single-day return and its date
# TODO 10: Markdown cell with 3 things you noticed

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib as plt

df = yf.download("SPY", start="2020-01-01", end="2025-01-01", auto_adjust=True)
df.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker             SPY         SPY         SPY         SPY       SPY
Date
2020-01-02  296.125305  296.143553  293.992353  294.912997  59151200
2020-01-03  293.882996  295.004175  292.688907  292.743596  77709700
2020-01-06  295.004059  295.086092  292.014249  292.132751  55653900
2020-01-07  294.174652  294.912981  293.727989  294.438973  40496400
2020-01-08  295.742493  296.954801  294.119989  294.366089  68296000

In [10]:
close = df['Close'].squeeze()


df['ret'] = close.pct_change()
df['vol20'] = df['ret'].rolling(20).std() * np.sqrt(252)

df.head(-3)

Price,Close,High,Low,Open,Volume,ret,vol20
Ticker,SPY,SPY,SPY,SPY,SPY,,
Date,,,,,,,
2020-01-02,296.125305,296.143553,293.992353,294.912997,59151200,NaN,NaN
2020-01-03,293.882996,295.004175,292.688907,292.743596,77709700,-0.007572,NaN
2020-01-06,295.004059,295.086092,292.014249,292.132751,55653900,0.003815,NaN
2020-01-07,294.174652,294.912981,293.727989,294.438973,40496400,-0.002812,NaN
2020-01-08,295.742493,296.954801,294.119989,294.366089,68296000,0.005330,NaN
...,...,...,...,...,...,...,...
2024-12-19,574.302002,581.063131,574.057034,579.456130,85919500,-0.000307,0.127047
2024-12-20,581.199951,585.722501,571.132258,571.977828,125716700,0.012011,0.133054
2024-12-23,584.680359,585.280077,577.768657,580.944331,57635800,0.005988,0.134338
2024-12-24,591.179016,591.218381,585.447129,586.027224,33160100,0.011115,0.139520
2024-12-26,591.218384,592.339150,588.013246,589.409328,41219100,0.000067,0.138411